name: E2E - Playwright

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd AIGC-Monitor
          npm ci

      - name: Install Playwright browsers
        run: |
          cd AIGC-Monitor
          npx playwright install --with-deps chromium

      - name: Run tests
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          cd AIGC-Monitor
          npm test -- --reporter=list,html,./reporters/slack-reporter.ts

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: AIGC-Monitor/playwright-report
          retention-days: 7


